export const PREVIOUS_TO_CURRENT_DAY = 'PREVIOUS_TO_CURRENT_DAY';
export const NEXT_TO_CURRENT_DAY = 'NEXT_TO_CURRENT_DAY';
export const UPDATE_PREVIOUS_DAY = 'UPDATE_PREVIOUS_DAY';
export const UPDATE_NEXT_DAY = 'UPDATE_NEXT_DAY';
